server:
  port: 8081

spring:
  application:
    name: service-provider
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.10:3306/education?useUnicode=true&characterEncoding=utf-8
    username: root
  profiles:
    active:
    - shiro


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/



